/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CS305_Asg_1;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.List;


public class SqlRunnerTest {
    Main sr = new Main();
    @BeforeEach
    void setUp() {
        sr.getConnection();
    }

    @AfterEach
    void tearDown() {
        sr = null;
    }

    @Test
    void selectOne() {
        Object[] queryParam = new Object[]{2};
        
        String queryId = "findActor";

        Object o1 = sr.selectOne(queryId, queryParam, xyz.class);
        xyz type_casted_o1 = (xyz) o1;
       assertEquals(type_casted_o1.first_name,"NICK");
    }

    @Test
    void selectMany() {
        Object[] queryParam = new Object[]{"CHRIS"};
        List<?> li = sr.selectMany("findLasttName", queryParam, pq.class);
        for(Object lang:li){
            pq type_casted_o1 = (pq) lang;
            assertEquals(type_casted_o1.last_name, "BRIDGES");
            break;
        }
    }

    @Test
    void insert() {
        Object[] queryParam = new Object[]{201,"Abc", "Xyz","2022-02-11 04:34:33"};
        int rows = sr.insert("addActor", queryParam);
        assertEquals(rows, 1);
    }

    @Test
    void update() {
        Object[] queryParam = new Object[]{"ABC",200};
        int rows = sr.insert("updateActorFirstName", queryParam);
        assertEquals(rows, 1);
    }

    @Test
    void delete() {
        Object[] queryParam = new Object[]{115};
        int rows = sr.insert("deleteActor", queryParam);
        assertEquals(rows, 1);
    }
}